name: Build 

on:
  push:
    branches:
      - master

env:
  DOCKER_REPO: openlaw/js-http-proxy
  IMAGE_NAME: openlaw/js-http-proxy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check available environment variables
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x
      
      - name: Build docker image and tag
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ secrets.PUB_REPO_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PUB_REPO_DOCKERHUB_ACCESS_TOKEN }}
          repository: ${{ env.DOCKER_REPO }}
          # Automatically tags the built image with the git short SHA prefixed with the branch name, e.g: vX.Y.Z, latest
          tags: ${{ env.GITHUB_REF_SLUG }}, latest
          # Only push image based on master branch
          push: ${{ startsWith(github.ref, 'refs/heads/master') }}